---
- name: Copiar Agente APM
  hosts: all
  gather_facts: no
  vars:
    # IMPORTANTE: Solo el nombre. Ansible busca en la carpeta 'files' por defecto
    archivo_fuente: "opentelemetry-javaagent.jar"
    destino_windows: 'C:\Tools\agente-apm'

  tasks:
    - name: 1. Asegurar que el directorio existe en Windows
      win_file:
        path: "{{ destino_windows }}"
        state: directory

    - name: 2. Copiar el archivo JAR al servidor
      win_copy:
        src: "{{ archivo_fuente }}"
        dest: "{{ destino_windows }}\\opentelemetry-javaagent.jar"

    - name: 3. Verificar que el archivo existe en el destino
      win_stat:
        path: "{{ destino_windows }}\\opentelemetry-javaagent.jar"
      register: jar_stat


