- name: Desplegar Agente APM desde Git a Windows
  hosts: all
  gather_facts: no
  vars:
    destino_windows: 'C:\Tools\agente-apm'
  tasks:
    - name: 1. Crear directorio de destino en Windows
      win_file:
        path: "{{ destino_windows }}"
        state: directory

    - name: Copiar un archivo de configuración
      ansible.windows.win_copy:
        src: /opentelemetry-javaagent.jar  # Ruta en tu máquina de control Ansible
        dest: C:\Tools\agente-apm # Ruta en el servidor Windows
        # Se pueden añadir opciones como:
        # backup: yes # Crea una copia de seguridad antes de sobrescribir
        # force: yes # Fuerza la copia si el archivo es idéntico
      register: copy_result

    - name: Mostrar resultado
      debug:
        var: copy_result
