- name: Limpieza NFS
  hosts: all
  gather_facts: false
  become: true  # Habilitar el modo 'become' para ejecutar comandos con sudo
  become_user: root
  tasks:
    - name: Ejecucion de SCRIPT PYTHON
      shell: python3 /var/shared/scripts/borardo.py > /var/shared/scripts/logs-borrado-nfs.log

      register: log_salida

    - name: Mostrar resultado
      debug:
        var:  log_salida.stdout_lines
