- name: Sacar major.gc.count de catalina.out
  hosts: all
  gather_facts: false
  become: true  # Habilitar el modo 'become' para ejecutar comandos con sudo
  become_user: root
  tasks:
- name: Utilizar grep y awk para tener información
      shell: grep 'major\\.gc\\.count=[0-9]\\+' /opt/ehcos-server/logs/catalina.out | awk -F',' '{{print substr($1, 1, 20),$14}}' | awk 'END {print}'
      register: log_salida

    - name: Mostrar resultado
      debug:
        var:  log_salida.stdout_lines


