- name: Reiniciar Servicio Tomcat
  hosts: all

  tasks:
    - name: Ejecutar reinicio
      win_shell: Get-Service -DisplayName "*tomcat*" | Stop-Service -force; Get-Service -DisplayName "*tomcat*" | Start-Service
      register: tomcat_service_name

    - name: Mostrar el resultado servicio Tomcat
      debug:
        var: tomcat_service_name.stdout
