- name: Reiniciar Servicio Tomcat
  hosts: all

  tasks:
    - name: Obtener nombre del servicio Tomcat
      win_shell: Get-Service | Where-Object { $_.DisplayName -like "*tomcat*" } | Select-Object -ExpandProperty DisplayName
      register: tomcat_service_name

    - name: Mostrar nombre del servicio Tomcat
      debug:
        var: tomcat_service_name.stdout

    - name: Detener servicio Tomcat
      win_service:
        name: "{{ tomcat_service_name.stdout }}"
        state: stopped
      register: stopped_service

    - name: Mostrar salida al detener servicio Tomcat
      debug:
        var: stopped_service

    - name: Iniciar servicio Tomcat
      win_service:
        name: "{{ tomcat_service_name.stdout }}"
        state: started
      register: started_service

    - name: Mostrar salida al iniciar servicio Tomcat
      debug:
        var: started_service
