---
- name: Verificar estado
  hosts: all
  vars:
  # servicio: "Tomcat"
  tasks:
  - name: Ejecutar comando
    win_command: powershell.exe  Get-Service -Displayname "*tomcat*"
    register: display_output
  - name: Mostrar salida del comando
    debug:
      var: display_output.stdout_lines
