---
- name: Verificar estado
  hosts: all
  become: yes
  vars:
  # servicio: "Tomcat"
  tasks:
  - name: Ejecutar comando
    become_user: adminsalud
    become_method: runas
    win_command: powershell.exe  Get-Service -Displayname "*tomcat*"
    register: display_output
  - name: Mostrar salida del comando
    debug:
      var: display_output.stdout_lines
